sensors:
 - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
   point_cloud_topic: /kinect/depth/points
   max_range: 2.5
   padding_offset: 0.08
   padding_scale: 1.5
   frame_subsample: 1
   point_subsample: 1
