string activity_state					   # Overall activity state
string name                                               # user names
string user_activity_state                                 # user activity states
string robot_state
string[] bad_bingo_numbers
help_indicators/triangle[] user_assistance_requests        # user assistance request states
geometry_msgs/PoseStamped robot_location                   # robot position relative to the map
help_indicators/triangle person_being_helped               # Current user being helped

