local_costmap:
  global_frame: /map #odom
  robot_base_frame: base_link
  static_map: false
  rolling_window: true
  width: 4.0
  height: 4.0
  resolution: 0.05

  #update_frequency: 5.0   
  #publish_frequency: 5.0  

